import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fork } from 'node:child_process';
import { setTimeout as pause } from 'node:timers/promises';
import { doc, getDocs, collection, setDoc, getDoc, terminate } from 'firebase/firestore';
import { deleteApp } from 'firebase/app';
import { goOffline, goOnline } from 'firebase/database';
import { signOut, signInWithCredential, GoogleAuthProvider } from 'firebase/auth';
import { content } from '../lib/firebase/merge.mjs';
const data = new Map();
globalThis.localStorage = { getItem: key => data.get(key) ?? null, setItem: (key, value) => data.set(key, String(value)), removeItem: key => data.delete(key) };
globalThis.window = new EventTarget();
Object.defineProperty(globalThis.navigator, 'onLine', { value: true, configurable: true });
const nativeFetch = globalThis.fetch;
globalThis.fetch = (url, init) => url === '/cards.json' ? Promise.resolve(Response.json(JSON.parse(readFileSync('public/cards.json', 'utf8')))) : nativeFetch(url, init);
const app = await import('../work/firebase-integration-client.mjs');
const sample = JSON.parse(readFileSync('tests/fixtures/starter-deck.json', 'utf8'));
const wait = async predicate => { for (let n = 0; n < 150; n++) { if (await predicate()) return; await pause(100); } throw new Error('Integration timeout'); };
test('actual Auth + Firestore SDK: local migration, cloud edits, conflict retention, logout and account isolation', { timeout: 45000 }, async () => {
  app.startSync();
  app.saveLocalDeck({ name: 'Offline deck', deck: sample });
  await app.emailLogin(`integration-${Date.now()}@example.test`, 'Only-for-local-emulator-123!', true);
  await wait(() => app.currentOwner()); await app.syncNow(true);
  assert.equal(app.listLocalDecks().length, 0, 'guest decks require deliberate import on shared device');
  app.importGuestDecks(); await app.syncNow(true);
  const owner = app.currentOwner(), row = app.listLocalDecks()[0];
  assert.equal(row.name, 'Offline deck');
  const remoteRef = doc(app.getFirebase().firestore, 'users', owner, 'decks', row.id);
  assert.equal((await getDoc(remoteRef)).data().name, 'Offline deck');
  Object.defineProperty(navigator, 'onLine', { value: false, configurable: true });
  app.saveLocalDeck({ ...row, name: 'Offline edit' });
  const remote = (await getDoc(remoteRef)).data();
  await setDoc(remoteRef, { ...remote, name: 'Second device edit', updatedAt: Date.now() + 1000 });
  Object.defineProperty(navigator, 'onLine', { value: true, configurable: true });
  await app.syncNow(true);
  assert.equal(app.listLocalDecks().length, 2, 'both concurrent edits preserved');
  assert.equal((await getDocs(collection(app.getFirebase().firestore, 'users', owner, 'decks'))).size, 2);
  const editing = app.getLocalDeck(row.id);
  await setDoc(remoteRef, { ...(await getDoc(remoteRef)).data(), name: 'Cloud update while editor open', updatedAt: Date.now() });
  await app.syncNow(true);
  app.saveLocalDeck({ id: row.id, name: 'Unsaved editor changes', deck: sample, _editorBase: content(editing) });
  await Promise.all([app.syncNow(), app.syncNow(true)]);
  assert.ok(app.listLocalDecks().some(row => row.name.startsWith('Cloud update while editor open')), 'a cloud pull cannot erase the unseen version when a stale editor saves');
  assert.ok(app.listLocalDecks().some(row => row.name === 'Unsaved editor changes'));
  app.saveUserData('settings', { theme: 'dark' });
  localStorage.setItem(app.draftKey(), JSON.stringify(sample));
  const backup = app.backupLocalData();
  app.saveUserData('settings', { theme: 'light' });
  app.importDecks(backup); await app.syncNow(true);
  assert.equal(app.getUserData('settings').theme, 'light', 'restore retains active settings');
  assert.ok(app.backupLocalData().data.some(row => row.id.startsWith('settings~') && row.value.theme === 'dark'), 'restore preserves alternate settings');
  assert.ok(app.listLocalDecks().some(row => row.name === '備份中的草稿'));
  await app.logout(); await wait(() => app.currentOwner() === null);
  assert.equal(app.listLocalDecks()[0].name, 'Offline deck', 'logout preserves guest original');
  const token = { sub: 'emulator-google-person', email: 'google-person@example.test', name: 'Google test', email_verified: true };
  await signInWithCredential(app.getFirebase().auth, GoogleAuthProvider.credential(JSON.stringify(token)));
  await wait(() => app.currentOwner() && app.currentOwner() !== owner); await app.syncNow(true);
  assert.equal(app.listLocalDecks().length, 0, 'another account cannot inherit first account data');
  assert.equal(app.backupLocalData().draft, null, 'another account cannot export the first account draft');
  await app.logout();
});
test('actual RTDB clients: create/join/ready, private views, stale action handling, disconnect and host reconnect', { timeout: 60000 }, async () => {
  await assert.rejects(() => app.loadRoom('INVALID'), /6 位/);
  await assert.rejects(() => app.loadRoom('ZZZZZZ'), /不存在|過期/);
  const room = await app.createRoom({ name: 'Host test', deck: sample });
  let current = room; let status = [];
  let stop = app.watchRoom(room.code, r => { current = r; }, message => status.push(message));
  const guest = fork('tests/firebase-integration-guest.mjs', [room.code], { stdio: ['ignore', 'inherit', 'inherit', 'ipc'] });
  const messages = [];
  guest.on('message', value => messages.push(value));
  try {
    await wait(() => messages.some(m => m.event === 'joined') || messages.some(m => m.error));
    assert.ok(!messages.some(m => m.error), JSON.stringify(messages));
    await wait(() => current.state.players.length === 2);
    current = await app.sendRoomAction(room.code, { expectedVersion: current.version, action: { type: 'ready', ready: true } });
    guest.send({ command: 'ready' });
    await wait(() => current.state.status === 'setup' || messages.some(m => m.error));
    assert.equal(current.state.status, 'setup');
    assert.ok(current.state.players[1].hand.every(card => card === null), 'guest hand identities are hidden in host UI projection');
    await assert.rejects(() => app.sendRoomAction(room.code, { expectedVersion: 1, action: { type: 'ready', ready: true } }));
    stop(); goOffline(app.getFirebase().database);
    await pause(300); goOnline(app.getFirebase().database);
    stop = app.watchRoom(room.code, r => { current = r; }, message => status.push(message));
    const reloaded = await app.loadRoom(room.code); assert.equal(reloaded.version, current.version);
    guest.send({ command: 'verify' }); await wait(() => messages.some(m => m.event === 'verified') || messages.some(m => m.error));
    assert.ok(messages.some(m => m.event === 'verified'), JSON.stringify(messages));
    current = await app.sendRoomAction(room.code, { expectedVersion: current.version, action: { type: 'setup', centerId: current.state.players[0].hand[0].id, backIds: [], bottomIds: [] } });
    guest.send({ command: 'setup' }); await wait(() => current.state.status === 'playing' || messages.some(m => m.error));
    assert.ok(!messages.some(m => m.error), JSON.stringify(messages));
    assert.equal(current.state.status, 'playing'); assert.equal(current.state.phase, 'cheer');
    if (current.state.firstPlayer === 0) current = await app.sendRoomAction(room.code, { expectedVersion: current.version, action: { type: 'choose', zone: 'center' } });
    else guest.send({ command: 'cheer' });
    await wait(() => current.state.phase === 'main' || messages.some(m => m.error));
    assert.equal(current.state.phase, 'main', 'both setups and first mandatory Cheer settle through RTDB');
  } finally { stop(); guest.kill(); }
});
test('AI engine runs locally and survives reload without Firebase writes', { timeout: 15000 }, async () => {
  const room = await app.createRoom({ name: 'Solo test', deck: sample, singlePlayer: true, opponentDeck: sample });
  assert.equal(room.state.mode, 'solo'); assert.ok(room.code.startsWith('AI-'));
  const reloaded = await app.loadRoom(room.code); assert.equal(reloaded.version, room.version); assert.equal(reloaded.state.status, 'setup');
});
test.after(async () => { goOffline(app.getFirebase().database); await terminate(app.getFirebase().firestore); await deleteApp(app.getFirebase().app); });
