import test from 'node:test';
import assert from 'node:assert/strict';
import {applyAction,publicRoomState} from '../lib/simulator/engine.mjs';
import {pool,state,inst,unit,fund,attack} from './fixtures/simulator-audit.mjs';
const act=(s,optionId,rng=()=>0)=>applyAction(s,0,{type:'choose',optionId},pool,rng);
function start(n='hBP01-043',fan=true){let s=state(n);fund(s.players[0].zones.center,pool.find(c=>c.number===n).arts[0].cost);if(fan)s.players[0].zones.center.attachments=[inst('hBP01-123','fan')];return s;}
test('Pekora fan rerolls entire three-die batch once, with private resumable data',()=>{
 let calls=0;const rng=()=>{calls++;return calls<=3?0:.99;};let s=applyAction(start(),0,attack,pool,rng);s=act(s,'roll',rng);
 assert.equal(s.pendingChoice.effect,'interactiveDice');assert.equal(calls,3);assert.equal(s.players[1].zones.center.damage,0);
 assert.ok(!JSON.stringify(publicRoomState(s,0)).includes('privateDiceAction'));assert.ok(!JSON.stringify(publicRoomState(s,1)).includes('baseline'));
 assert.throws(()=>applyAction(s,1,{type:'choose',optionId:'reroll:fan'},pool,rng));assert.throws(()=>act(s,'reroll:missing',rng));
 s=act(JSON.parse(JSON.stringify(s)),'reroll:fan',rng);assert.equal(calls,6);assert.equal(s.players[0].archive.filter(c=>c.id==='fan').length,1);assert.equal(s.players[0].turnEvents.diceRollCount,3);assert.deepEqual(s.players[0].turnEvents.dice.map(c=>c.value),[6,6,6]);assert.equal(s.players[1].zones.center.damage,60);assert.ok(!s.privateDiceAction);
});
test('Pekora may accept without spending the fan',()=>{let s=applyAction(start(),0,attack,pool,()=>0);s=act(s,'roll');s=act(s,'accept');assert.equal(s.players[0].zones.center.attachments.length,1);assert.equal(s.players[1].zones.center.damage,90);});
test('AZKi declares before randomness and pays only once',()=>{let s=start('hBP01-043',false);s.players[0].oshi=inst('hSD01-002');s.players[0].holoPower=[1,2,3].map(i=>inst('AUDIT-DUMMY','power'+i));let calls=0;const rng=()=>{calls++;return .99;};s=applyAction(s,0,attack,pool,rng);s=act(s,'roll',rng);assert.equal(calls,0);assert.equal(s.pendingChoice.effect,'interactiveDice');s=act(s,'declare:1',rng);assert.equal(calls,3);assert.equal(s.players[0].holoPower.length,0);assert.equal(s.players[0].archive.length,3);assert.equal(s.players[0].oshiSkillTurn,3);assert.deepEqual(s.players[0].turnEvents.dice.map(c=>c.value),[1,6,6]);assert.equal(s.players[1].zones.center.damage,70);});
test('Matsurisu modifies one die of an Oshi ability and spends only its selected fan',()=>{let s=state();s.phase='main';s.players[0].oshi=inst('hBP06-008');s.players[0].holoPower=Array.from({length:8},(_,i)=>inst('AUDIT-DUMMY','power'+i));s.players[0].zones.back1=unit('AUDIT-DUMMY',{attachments:[inst('hBP06-103','matsu')]});s=applyAction(s,0,{type:'oshiSkill'},pool,()=>0);assert.equal(s.pendingChoice.effect,'interactiveDice');s=act(s,'four:0:matsu');assert.equal(s.players[0].turnEvents.dice[0].value,4);assert.ok(s.players[0].archive.some(c=>c.id==='matsu'));assert.ok(!s.players[0].zones.back1.attachments.length);});
test('Pekora stacked Arts reroll discards the entire sum and draws only once',()=>{let s=start('hBP05-016');s.players[0].zones.center.stack.unshift(inst('AUDIT-DUMMY','under1'),inst('AUDIT-DUMMY','under2'));s=applyAction(s,0,attack,pool,()=>0);assert.equal(s.pendingChoice.effect,'pekoraStackBatch');s=act(s,'2');s=act(s,'reroll:fan',()=>.99);assert.deepEqual(s.players[0].turnEvents.dice.map(c=>c.value),[6,6]);assert.equal(s.players[1].zones.center.damage,240);assert.equal(s.players[0].hand.length,2);});
test('Matsurisu chooses one die in a first-generation batch',()=>{const c=pool.find(c=>c.number==='hBP04-082');const base=pool.find(x=>x.jpName===c.jpName&&x.stage==='1st');let s=state(base.number);s.phase='main';s.players[0].zones.center.attachments=[inst('hBP06-103','matsu')];s.players[0].hand=[inst(c.number,'bloom')];s.players[0].zones.back1=unit(pool.find(c=>c.group==='holomem'&&c.tags?.includes('#1期生')&&c.jpName!==base.jpName).number);s=applyAction(s,0,{type:'play',cardId:'bloom'},pool,()=>0);s=applyAction(s,0,{type:'choose',zone:'center'},pool,()=>0);assert.equal(s.pendingChoice.effect,'matsuriShoppingRoll');s=act(s,'2');assert.equal(s.pendingChoice.effect,'interactiveDice');s=act(s,'four:1:matsu');assert.deepEqual(s.players[0].turnEvents.dice.map(c=>c.value),[1,4]);});
test('Pekora fan on another copy cannot reroll the Arts source',()=>{let s=start('hBP01-043',false);s.players[0].zones.back1=unit('hBP01-043',{stack:[inst('hBP01-043','other')],attachments:[inst('hBP01-123','otherfan')]});s=applyAction(s,0,attack,pool,()=>0);s=act(s,'roll');assert.equal(s.pendingChoice,null);assert.equal(s.players[0].zones.back1.attachments.length,1);});
test('AZKi declaration is consumed before a fan reroll',()=>{let s=start();s.players[0].oshi=inst('hSD01-002');s.players[0].holoPower=[1,2,3].map(i=>inst('AUDIT-DUMMY','power'+i));s=applyAction(s,0,attack,pool,()=>.99);s=act(s,'roll',()=>.99);s=act(s,'declare:1',()=>.99);s=act(s,'reroll:fan',()=>.99);assert.deepEqual(s.players[0].turnEvents.dice.map(c=>c.value),[6,6,6]);assert.equal(s.players[0].archive.length,4);});
