import fs from "node:fs";
import path from "node:path";

const cardsPath = path.resolve(process.argv[2] || "public/cards.json");
const outputPath = path.resolve(process.argv[3] || "scripts/name-zh.json");
const payload = JSON.parse(fs.readFileSync(cardsPath, "utf8"));

// Localized talent names cross-checked against the online hololive talent list.
// EN and ID talents use their official Latin-alphabet names; Japanese names remain in the card data.
const talentNames = {
  "AIこより": "AI小夜璃",
  AZKi: "AZKi",
  FUWAMOCO: "FUWAMOCO",
  IRyS: "IRyS",
  miComet: "miComet（星櫻組）",
  SorAZ: "SorAZ（時乃空與AZKi）",
  "アーニャ・メルフィッサ": "Anya Melfissa",
  "アイラニ・イオフィフティーン": "Airani Iofifteen",
  "アキ・ローゼンタール": "亞綺·羅森塔爾",
  "アユンダ・リス": "Ayunda Risu",
  "エリザベス・ローズ・ブラッドフレイム": "Elizabeth Rose Bloodflame",
  "オーロ・クロニー": "Ouro Kronii",
  "カエラ・コヴァルスキア": "Kaela Kovalskia",
  "クレイジー・オリー": "Kureiji Ollie",
  "こぼ・かなえる": "Kobo Kanaeru",
  "さくらみこ": "櫻巫女",
  "シオリ・ノヴェラ": "Shiori Novella",
  "ジジ・ムリン": "Gigi Murin",
  "セシリア・イマーグリーン": "Cecilia Immergreen",
  "ときのそら": "時乃空",
  "ネリッサ・レイヴンクロフト": "Nerissa Ravencroft",
  "パヴォリア・レイネ": "Pavolia Reine",
  "ハコス・ベールズ": "Hakos Baelz",
  "フワワ・アビスガード": "Fuwawa Abyssguard",
  "ベスティア・ゼータ": "Vestia Zeta",
  "ムーナ・ホシノヴァ": "Moona Hoshinova",
  "モココ・アビスガード": "Mococo Abyssguard",
  "ラオーラ・パンテーラ": "Raora Panthera",
  "ラプラス・ダークネス": "拉普拉斯·暗黑",
  "ラムダック": "Lambduck（拉姆鴨）",
  "ロボ子さん": "蘿蔔子",
  "ワトソン・アメリア": "Watson Amelia",
  "一伊那尓栖": "Ninomae Ina'nis",
  "一条莉々華": "一條莉莉華",
  "七詩ムメイ": "Nanashi Mumei",
  "不知火フレア": "不知火芙蕾雅",
  "儒烏風亭らでん": "儒烏風亭螺鈿",
  "兎田ぺこら": "兔田佩克拉",
  "博衣こより": "博衣小夜璃",
  "古石ビジュー": "Koseki Bijou",
  "夏色まつり": "夏色祭",
  "大神ミオ": "大神澪",
  "大空スバル": "大空昴",
  "天音かなた": "天音彼方",
  "姫森ルーナ": "姬森璐娜",
  "宝鐘マリン": "寶鐘瑪琳",
  "小鳥遊キアラ": "Takanashi Kiara",
  "尾丸ポルカ": "尾丸波爾卡",
  "常闇トワ": "常闇永遠",
  "戌神ころね": "戌神沁音",
  "星街すいせい": "星街彗星",
  "桃鈴ねね": "桃鈴音音",
  "森カリオペ": "Mori Calliope",
  "水宮枢": "水宮樞",
  "沙花叉クロヱ": "沙花叉克蘿伊",
  "火威青": "火威青",
  "猫又おかゆ": "貓又小粥",
  "獅白ぼたん": "獅白牡丹",
  "癒月ちょこ": "癒月巧可",
  "白上フブキ": "白上吹雪",
  "白銀ノエル": "白銀諾艾爾",
  "百鬼あやめ": "百鬼綾目",
  "紫咲シオン": "紫咲詩音",
  "綺々羅々ヴィヴィ": "綺綺羅羅薇薇",
  "虎金妃笑虎": "虎金妃笑虎",
  "角巻わため": "角卷綿芽",
  "赤井はあと": "赤井心",
  "輪堂千速": "輪堂千速",
  "轟はじめ": "轟一",
  "雪花ラミィ": "雪花菈米",
  "音乃瀬奏": "音乃瀨奏",
  "響咲リオナ": "響咲莉歐娜",
  "風真いろは": "風真伊呂波",
  "魔法少女かなた": "魔法少女彼方",
  "魔法少女クロヱ": "魔法少女克蘿伊",
  "魔法少女シオン": "魔法少女詩音",
  "魔法少女マリン": "魔法少女瑪琳",
  "魔法少女みこ": "魔法少女巫女",
  "魔法少女ルーナ": "魔法少女璐娜",
  "鷹嶺ルイ": "鷹嶺琉依",
};

const manualNames = {
  Advent: "Advent（降臨）",
  BAZO: "BAZO（巴佐）",
  "Bloom＆Gloom": "綻放與幽暗",
  Boros: "Boros（波羅斯）",
  Chattino: "Chattino（恰提諾）",
  Cilus: "Cilus（西勒斯）",
  "Death-sensei": "死神老師",
  "First Gravity": "初始重力",
  "FLOW GLOW": "FLOW GLOW（流光）",
  GEOW: "GEOW（吉歐）",
  GuyRyS: "GuyRyS（蓋莉絲）",
  holoAN: "holoAN（官方新聞）",
  "hololive Mythology": "hololive神話",
  HOLOTORI: "HOLOTORI（鳥系組合）",
  "IDENTIFY -AREA 15-": "身分識別－第15區－",
  Jailbird: "Jailbird（獄友）",
  Justice: "Justice（正義）",
  "JUSTICE, JUST LIKE THAT!!!!": "正義，就是如此!!!!",
  KFP: "KFP（琪亞拉炸雞店）",
  Kotori: "Kotori（小鳥）",
  Kronies: "Kronies（克洛尼粉絲）",
  Myth: "Myth（神話）",
  Otomo: "Otomo（御供）",
  Popo: "Popo（波波）",
  Promise: "Promise（承諾）",
  ReGLOSS: "ReGLOSS（再光澤）",
  Riscot: "Riscot（莉絲吉祥物）",
  Risuners: "Risuners（莉絲粉絲）",
  Ruffians: "Ruffians（惡棍們）",
  SSRB: "SSRB（獅白粉絲）",
  Takodachi: "Takodachi（章魚伴）",
  Tatang: "Tatang（塔唐）",
  Thorn: "Thorn（荊棘）",
  UDIN: "UDIN（烏丁）",
  "We are ReGLOSS": "我們是ReGLOSS",
  "WHAT'S UP!!!!! KEEEEEP GROWING!!!!!": "怎麼啦!!!!! 繼續成長!!!!!",
  Zecretary: "Zecretary（澤塔秘書）",
  "白エール": "白色應援",
  "緑エール": "綠色應援",
  "赤エール": "紅色應援",
  "青エール": "藍色應援",
  "紫エール": "紫色應援",
  "黄エール": "黃色應援",
};

// Player-facing card-title review. Proper names stay recognizable, with a Chinese
// explanation where a literal translation would make the card harder to identify.
const reviewedCardNames = {
  "2人あわせてラムダック！": "兩人合體Lambduck！",
  "35P": "35P（櫻巫女粉絲）",
  Advent: "Advent（降臨）",
  "ASMRマイク": "ASMR麥克風",
  BAZO: "BAZO（巴佐）",
  "Bloom＆Gloom": "綻放與幽暗",
  Boros: "Boros（波羅斯）",
  Chattino: "Chattino（恰提諾）",
  Cilus: "Cilus（西勒斯）",
  "Death-sensei": "死神老師",
  "First Gravity": "初始重力",
  "FLOW GLOW": "FLOW GLOW（流光）",
  "FPS配信": "FPS直播",
  GEOW: "GEOW（吉歐）",
  GuyRyS: "GuyRyS（蓋莉絲）",
  holoAN: "holoAN（官方新聞）",
  "HOLOLIVE FANTASY": "hololive FANTASY（幻想組）",
  "hololive Mythology": "hololive Mythology（神話）",
  HOLOTORI: "HOLOTORI（鳥系組合）",
  "IDENTIFY -AREA 15-": "身分識別－第15區－",
  Jailbird: "Jailbird（獄友）",
  Justice: "Justice（正義）",
  "JUSTICE, JUST LIKE THAT!!!!": "正義，就是如此!!!!",
  KFP: "KFP（琪亞拉炸雞店）",
  Kotori: "Kotori（小鳥）",
  Kronies: "Kronies（克洛尼粉絲）",
  Myth: "Myth（神話）",
  Otomo: "Otomo（御供）",
  Popo: "Popo（波波）",
  Promise: "Promise（承諾）",
  ReGLOSS: "ReGLOSS（再光澤）",
  Riscot: "Riscot（莉絲吉祥物）",
  Risuners: "Risuners（莉絲粉絲）",
  Ruffians: "Ruffians（惡棍們）",
  "SorAZセレブレーション": "SorAZ慶典",
  SSRB: "SSRB（獅白粉絲）",
  Takodachi: "Takodachi（章魚夥伴）",
  Tatang: "Tatang（塔唐）",
  Thorn: "Thorn（荊棘）",
  UDIN: "UDIN（烏丁）",
  "We are ReGLOSS": "我們是ReGLOSS",
  "WHAT'S UP!!!!! KEEEEEP GROWING!!!!!": "怎麼啦!!!!! 繼續成長!!!!!",
  Zecretary: "Zecretary（澤塔秘書）",
  "アーカイブパソコン": "檔案電腦",
  "アイドルサインペン": "偶像簽字筆",
  "アイドルマイク": "偶像麥克風",
  "アキ・ローゼンタールの斧": "亞綺·羅森塔爾的斧頭",
  "あとは任せた！": "接下來就拜託了！",
  "ありよりのアリゲーター": "超級可以的鱷魚",
  "アンコール": "安可",
  "あん肝": "安肝（時乃空吉祥物）",
  "いたずらなRuffians": "淘氣的Ruffians",
  "イヌ": "狗狗",
  "いろはにほへっと あやふぶみ": "伊呂波香步・綾吹組",
  "うぱお": "UPAO（烏帕歐）",
  "うまみー！": "好吃～！",
  "えびふらいおん": "炸蝦獅",
  "エルフレンド": "Elf-friend（精靈朋友）",
  "エレガントパソコン": "優雅電腦",
  "おかにゃん": "Okayanyan（岡喵）",
  "おにぎりゃー": "飯糰軍",
  "おるやんけ": "Orunyanke（奧路揚）",
  "カスタムパソコン": "客製化電腦",
  "かなた建設": "彼方建設",
  "カラス": "烏鴉",
  "カワイイスタジャン": "可愛棒球外套",
  "がんも": "Ganmo（雁模）",
  "ギラファノコギリクワガタ": "長頸鹿鋸鍬形蟲",
  "ギリわるロボ": "勉強算壞的機器人",
  "クールなパーカー": "帥氣連帽衫",
  "クリエイターパソコン": "創作者電腦",
  "クロスインパクト": "交叉衝擊",
  "ゲーミングパソコン": "電競電腦",
  "けはい": "氣息",
  "ゴージャスパソコン": "豪華電腦",
  "コールアンドレスポンス": "呼喊與回應",
  "ごきげんカレー": "開心咖哩",
  "ココロ": "心心（Kokoro）",
  "こよりの助手くん": "小夜璃的助手君",
  "ころねすきー": "Koronesuki（沁音粉絲）",
  "サブパソコン": "備用電腦",
  "しめじダンス": "真姬菇之舞",
  "じゃあ敵だね": "那就是敵人了",
  "しょこら": "Chocola（巧克拉）",
  "ジョブズ": "Jobs（賈伯斯）",
  "スーパーパソコン": "超級電腦",
  "スゴイパソコン": "厲害電腦",
  "すこん部": "すこん部（吹雪粉絲）",
  "ステラ": "Stella（史黛拉）",
  "スバちょこルーナ": "昴巧可璐娜",
  "スバルドダック": "昴鴨",
  "スバ友": "昴友",
  "だいふく": "大福",
  "ﾁｬｷ丸": "Chaki丸（茶木丸）",
  "ちゃま旅": "哈洽馬之旅",
  "ちょこのオムライス": "巧可的蛋包飯",
  "ちょこのなすユッケ": "巧可的生拌茄子",
  "ちょこのビーフストロガノフ": "巧可的俄式酸奶牛肉",
  "ツートンカラーパソコン": "雙色電腦",
  "デュアルモニターパソコン": "雙螢幕電腦",
  "ドクロくん": "骷髏君",
  "ドッキリうさぎ": "驚喜兔",
  "ドローイングストリーム": "繪畫直播",
  "ネジマキツネ": "發條狐狸",
  "ねっ子": "根子（桃鈴音音粉絲）",
  "ねぽらぼ": "NePoLaBo（五期生組合）",
  "ネリッサ・レイヴンクロフトの杖": "納瑞莎·雷文克羅夫特的法杖",
  "はあとん": "Haato豚（赤井心粉絲）",
  "バカタレサーカス": "笨蛋馬戲團",
  "ハトタウロス": "HatoTaurus（鴿牛怪）",
  "パパは仕事を辞める": "爸爸要辭職了",
  "ばんぺん": "Banpen（番企鵝）",
  "ビッグゴッドミオーンの占い": "大神澪的占卜",
  "ビビ": "Vivi（薇薇）",
  "ファンミーティング": "粉絲見面會",
  "フェイバリットパソコン": "最愛電腦",
  "ふぐ太郎": "河豚太郎",
  "ふつうのパソコン": "普通電腦",
  "フトイヌ": "胖狗",
  "ブヒー！": "噗嘻！",
  "フブチュン": "Fubuchun（吹啾）",
  "フブラ": "Fubura（吹拉）",
  "ブルームステージ": "綻放舞台",
  "フレンド": "朋友",
  "フレンドリーパソコン": "友善電腦",
  "フロンティアスピリット": "開拓精神",
  "ペロ": "Pero（佩羅）",
  "ペンライト": "應援棒",
  "ぽこべぇ": "PokoBe（ぽこべぇ）",
  "ホソイヌ": "瘦狗",
  "ぽよ余": "Poyo余",
  "ホロキャップ": "hololive鴨舌帽",
  "ホロスパークリング": "hololive氣泡飲",
  "ホロマント": "hololive斗篷",
  "ホロライブ インドネシア2期生": "hololive Indonesia 2期生",
  "ホロライブ0期生": "hololive 0期生",
  "ホロライブ1期生": "hololive 1期生",
  "ホロライブ2期生": "hololive 2期生",
  "ホロライブ4期生": "hololive 4期生",
  "ホロライブインドネシア1期生": "hololive Indonesia 1期生",
  "ホロライブインドネシア3期生": "hololive Indonesia 3期生",
  "ホロライブゲーマーズ": "hololive GAMERS",
  "ホロライブ言えるかな？": "你能說出hololive嗎？",
  "ホロリスの輪": "holo粉絲之環",
  "まいたけダンス": "舞茸之舞",
  "マグチ": "Maguchi（馬口）",
  "マスコットキャッチャー": "吉祥物夾娃娃機",
  "まつたけダンス": "松茸之舞",
  "まつりす": "Matsurisu（夏色祭粉絲）",
  "マネちゃん": "經紀人醬",
  "マヨネーズちゅっちゅっ": "啾啾美乃滋",
  "ミオファ": "MioFa（大神澪粉絲）",
  "みこだにぇー": "MikoDanye（巫女吉祥物）",
  "みっころね24": "Mikkorone 24（巫女沁音24）",
  "ミテイル": "Miteiru（米泰魯）",
  "み俺恥": "看得我都害羞",
  "ムーナびと": "Moona粉絲",
  "やめなー": "快住手～",
  "ゆび": "手指",
  "ライブスタッフ": "現場工作人員",
  "ライフル": "步槍",
  "リコーダー": "直笛",
  "りっちしょこらのハンバーグ": "Rich Chocola的漢堡排",
  "ルイ友": "琉依友",
  "ルーナイト": "璐娜騎士",
  "レトロパソコン": "復古電腦",
  "ロゼ隊": "羅森隊",
  "ろぼさー": "蘿蔔子粉絲",
  "ワークアウト": "健身訓練",
  "わくわくいたずらタイム": "興奮惡作劇時間",
  "わためいと": "綿芽粉絲",
  "阿修羅＆羅刹": "阿修羅與羅剎",
  "愛情いっぱい召し上がれ♪": "滿載愛意，請享用♪",
  "塩っ子": "鹽子（紫咲詩音粉絲）",
  "開拓者": "開拓者",
  "角巻わためのハープ": "角卷綿芽的豎琴",
  "角巻わためのハンマー": "角卷綿芽的槌子",
  "鬼神刀「阿修羅」": "鬼神刀「阿修羅」",
  "牛丼": "牛丼",
  "金時": "金時",
  "月と兎の物語": "月與兔的故事",
  "限界飯": "極限飯",
  "古代武器": "古代武器",
  "座員": "座員（尾丸波爾卡粉絲）",
  "作業用パソコン": "工作用電腦",
  "山田ルイ54世": "山田琉依54世",
  "思い出のドーナツショップ": "回憶中的甜甜圈店",
  "紫咲シオンの魔法のステッキ": "紫咲詩音的魔法杖",
  "時の支配者 -Promise-": "時間支配者－Promise－",
  "春先のどか": "春先和香",
  "森カリオペの鎌": "森美聲的鐮刀",
  "星街すいせいのマイク": "星街彗星的麥克風",
  "石の斧": "石斧",
  "雪民": "雪民（雪花菈米粉絲）",
  "脱獄を果たした共犯者たち": "成功越獄的共犯者們",
  "鍛冶ハンマー": "鍛造槌",
  "泥棒建設": "小偷建設",
  "凸待ち": "等待來電",
  "鈍器でぶっ叩くわよ！": "用鈍器揍你！",
  "白銀ノエルのメイス": "白銀諾艾爾的權杖",
  "白銀聖騎士団": "白銀聖騎士團",
  "爆発の魔法": "爆炸魔法",
  "破滅の呪文": "毀滅咒語",
  "晩酌配信": "晚酌直播",
  "秘密結社holoX": "秘密結社holoX",
  "不知火建設": "不知火建設",
  "魔法のタンス": "魔法衣櫃",
  "野うさぎ同盟": "野兔同盟",
  "優しいモンスター": "溫柔的怪物",
  "緑の試験管": "綠色試管",
  "白エール": "白色應援",
  "緑エール": "綠色應援",
  "赤エール": "紅色應援",
  "青エール": "藍色應援",
  "紫エール": "紫色應援",
  "黄エール": "黃色應援",
};

async function translateName(name) {
  const params = new URLSearchParams({ client: "gtx", sl: "ja", tl: "zh-TW", dt: "t", q: name });
  const response = await fetch(`https://translate.googleapis.com/translate_a/single?${params}`);
  if (!response.ok) throw new Error(`Translation failed for ${name}: ${response.status}`);
  const result = await response.json();
  return result[0].map((segment) => segment[0]).join("").trim();
}

const uniqueNames = [...new Set(payload.cards.map((card) => card.jpName || card.name).filter(Boolean))];
const translations = { ...talentNames, ...manualNames, ...reviewedCardNames };
const missing = uniqueNames.filter((name) => !translations[name]);
if (missing.length > 0) console.log(`Online fallback for: ${missing.join("、")}`);

let cursor = 0;
const workers = Array.from({ length: 6 }, async () => {
  while (cursor < missing.length) {
    const name = missing[cursor++];
    translations[name] = (await translateName(name)) || name;
  }
});
await Promise.all(workers);

const sorted = Object.fromEntries(
  Object.entries(translations)
    .filter(([name]) => uniqueNames.includes(name))
    .sort(([left], [right]) => left.localeCompare(right, "ja")),
);
fs.writeFileSync(outputPath, `${JSON.stringify(sorted, null, 2)}\n`);

for (const card of payload.cards) {
  const translatedName = sorted[card.jpName] || card.name || card.jpName || card.number;
  card.name = card.simOnly && /HoloSim 異圖/.test(card.name)
    ? `${translatedName}（HoloSim 異圖）`
    : translatedName;
}

payload.meta.traditionalChineseCards = payload.cards.filter((card) => sorted[card.jpName]).length;
payload.meta.note = "卡名採繁中翻譯，EN／ID 成員採官方英文名；技能為非官方繁中閱讀翻譯，正式對戰與裁定以官方日文資料為準。";
fs.writeFileSync(cardsPath, JSON.stringify(payload));
console.log(`Wrote ${Object.keys(sorted).length} localized card names to ${outputPath}`);
