export const TOP_LOOK_EFFECTS = Object.freeze({
  "hBP01-102": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#歌"] } },
  "hBP01-109": { count: 4, handLimit: 6, match: { group: "holomem", names: ["兎田ぺこら", "ムーナ・ホシノヴァ"] } },
  "hBP01-111": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#ID3期生"] } },
  "hBP01-113": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#Promise"] } },
  "hBP02-075": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#絵"] } },
  "hBP02-078": { count: 4, handLimit: 6, match: { group: "holomem", names: ["天音かなた", "AZKi", "沙花叉クロヱ"] } },
  "hBP02-080": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#秘密結社holoX"] } },
  "hBP02-081": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#ID2期生"] } },
  "hBP02-082": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#ゲーマーズ"] } },
  "hBP02-085": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#3期生"] } },
  "hBP03-085": { count: 4, groups: [{ required: true, label: "Debut Holomen", match: { group: "holomem", stages: ["Debut"] } }, { required: true, label: "1st Holomen", match: { group: "holomem", stages: ["1st"] } }] },
  "hBP03-090": { count: 4, match: { group: "holomem", stages: ["Debut"] } },
  "hBP03-091": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#ID1期生"] } },
  "hBP03-092": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#0期生"] } },
  "hBP03-093": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#4期生"] } },
  "hBP03-094": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#シューター"] } },
  "hBP04-090": { count: 4, handLimit: 6, groups: [{ label: "Holomen", match: { group: "holomem" } }, { label: "工具／吉祥物／粉絲", match: { typeCodes: ["supportTool", "supportMascot", "supportFan"] } }] },
  "hBP04-092": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#5期生"] } },
  "hBP04-093": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#2期生"] } },
  "hBP04-096": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#Advent"] } },
  "hBP05-077": { count: 4, handLimit: 6, match: { group: "holomem", names: ["白上フブキ", "不知火フレア", "角巻わため", "尾丸ポルカ"] } },
  "hBP05-078": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#お酒"] } },
  "hBP06-091": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#1期生"] } },
  "hBP08-100": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#Myth"] } },
  "hPR-002": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#ReGLOSS"] } },
  "hSD01-018": { count: 5, max: 1, required: true, match: { group: "support", limited: true } },
  "hSD01-021": { count: 4, handLimit: 6, match: { group: "holomem", names: ["ときのそら", "AZKi"] } },
  "hSD02-012": { count: 4, handLimit: 6, match: { group: "holomem", names: ["白上フブキ", "大神ミオ", "百鬼あやめ"] } },
  "hSD03-012": { count: 4, handLimit: 6, match: { group: "holomem", names: ["猫又おかゆ", "鷹嶺ルイ", "大神ミオ", "白上フブキ", "ラプラス・ダークネス", "戌神ころね"] } },
  "hSD04-012": { count: 4, handLimit: 6, match: { group: "holomem", names: ["大空スバル", "癒月ちょこ", "姫森ルーナ"] } },
  "hSD07-014": { count: 4, handLimit: 6, match: { group: "holomem", names: ["不知火フレア", "尾丸ポルカ", "さくらみこ", "星街すいせい", "白銀ノエル"] } },
  "hSD10-012": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#FLOW GLOW"] } },
  "hSD13-016": { count: 4, handLimit: 6, match: { group: "holomem", tags: ["#Justice"] } },
});

export const DECK_SEARCH_EFFECTS = Object.freeze({
  "hBP01-103": { costHoloPower: 1, match: { group: "holomem", stages: ["Debut", "1st"], sameOshiColor: true, excludeBuzz: true } },
  "hBP03-084": { required: true, costHoloPower: 1, match: { group: "holomem", stages: ["1st"], sameOshiColor: true } },
  "hBP03-089": { required: true, match: { typeCodes: ["supportFan"] } },
  "hBP04-095": { match: { typeCodes: ["supportMascot"] } },
  "hSD01-019": { costStageCheer: 1, required: true, match: { group: "holomem", stages: ["1st", "2nd"], excludeBuzz: true } },
});

export const SIMPLE_SUPPORT_EFFECTS = Object.freeze({
  "hSD01-016": "drawThree",
  "hSD01-017": "resetHandFive",
  "hBP01-105": "cheerStick",
  "hBP01-106": "swapOwnCenter",
  "hBP01-107": "archiveCheerReturn",
  "hBP03-087": "moveStageCheer",
});

// Cards below share the same small set of simulator primitives (card moves,
// stage targets, Cheer targets, damage, healing and temporary modifiers).  The
// value is intentionally descriptive: it is also used by the coverage tests so
// a newly-added support card cannot silently fall back to manual resolution.
export const EXTENDED_SUPPORT_EFFECTS = Object.freeze({
  "hBP01-108": "swapOpponentCenter",
  "hBP01-110": "bluntWeapon",
  "hBP01-112": "mischiefDamage",
  "hBP02-076": "customComputer",
  "hBP02-077": "retroComputer",
  "hBP02-079": "explosionMagic",
  "hBP02-083": "magicWardrobe",
  "hBP02-084": "mikkorone24",
  "hBP03-086": "dualMonitorComputer",
  "hBP04-089": "twoColorComputer",
  "hBP04-091": "limitMeal",
  "hBP04-094": "maitakeDance",
  "hBP05-074": "friendlyComputer",
  "hBP05-075": "gyudon",
  "hBP05-076": "chocoStroganoff",
  "hBP05-079": "shyStream",
  "hBP06-085": "favoriteComputer",
  "hBP06-086": "madeWithLove",
  "hBP06-087": "realMushroomDance",
  "hBP06-088": "surpriseRabbit",
  "hBP06-092": "chuchuMayonnaise",
  "hBP06-094": "fitnessTraining",
  "hBP06-095": "area15Identity",
  "hBP06-096": "lambduck",
  "hBP07-091": "fieldStaff",
  "hBP07-092": "archiveComputer",
  "hBP07-093": "umamy",
  "hBP07-094": "badRobot",
  "hBP07-095": "crossImpact",
  "hBP07-096": "haachamaTrip",
  "hBP07-097": "promiseTimeRuler",
  "hBP07-098": "mioFortune",
  "hBP07-099": "puhihi",
  "hBP07-100": "frontierSpirit",
  "hBP08-090": "elegantComputer",
  "hBP08-091": "creatorComputer",
  "hBP08-092": "donutMemory",
  "hBP08-093": "chocoEggplant",
  "hBP08-094": "dadIsQuitting",
  "hBP08-095": "destructionSpell",
  "hBP08-096": "gentleMonster",
  "hBP08-097": "richChocolaHamburg",
  "hBP08-098": "hololiveMythology",
  "hBP08-099": "holotori",
  "hBP08-101": "weAreRegloss",
  "hEB01-025": "summerComputer",
  "hEB01-026": "kumarine",
  "hEB01-027": "summerLive",
  "hEB01-028": "watermelonSmash",
  "hEB01-029": "splashShoot",
  "hEB01-031": "waterPlay",
  "hEB01-032": "starStarT",
  "hSD01-020": "holoFanCircle",
  "hSD04-013": "chocoOmelette",
  "hSD10-011": "keepGrowing",
  "hSD12-015": "successfulEscape",
  "hSD13-017": "justiceIsThis",
  "hSD14-010": "holoAN",
  "hSD15-010": "matsutakeDance",
  "hSD17-010": "stella",
  "hSD19-010": "happyCurry",
});

export const AUTOMATED_SUPPORT_CARDS = Object.freeze([
  ...Object.keys(TOP_LOOK_EFFECTS),
  ...Object.keys(DECK_SEARCH_EFFECTS),
  ...Object.keys(SIMPLE_SUPPORT_EFFECTS),
  ...Object.keys(EXTENDED_SUPPORT_EFFECTS),
  "hBP01-104",
  "hEB01-030",
  "hBP03-088",
  "hBP05-080",
  "hBP06-089",
  "hBP06-090",
  "hBP06-093",
]);

export function isAutomatedSupportCard(number) {
  return AUTOMATED_SUPPORT_CARDS.includes(number);
}




